server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aliCh10/Wind_Facture 
          clone-on-start: true